---
- name: Cockpit install
  yum: name='cockpit'
       enablerepo=epel
       state=present
  notify:
  - cockpit_startup
  - cockpit_start

- name: firewall configure
  command: firewall-cmd --permanent --zone=public --add-service=cockpit
  notify:
  - firewall_reload