---
- name: X Windows install
  yum: name="@X Window system"
       enablerepo=epel
       state=latest

- name: Fonts install
  yum: name="@Fonts"
       enablerepo=epel
       state=latest

- name: Xfce install
  yum: name="@Xfce"
       enablerepo=epel
       state=latest
  notify:
  - xfce_startup

- name: gdm install
  yum: name="gdm"
       state=latest

- name: start in runlevel 5
  command: /bin/systemctl set-default graphical.target
  
#sed -i -e "s/id:3:initdefault:/id:5:initdefault:/g" /etc/inittab