---
- name: Development Tools install
  yum: name="@Development Tools"
       state=latest

- name: 1C Postgres Sourse install
  yum: name=http://v8.1c.ru/overview/postgresql_patches/9-4-2/postgresql94-9.4.2-1.1c.src.rpm
       state=present

- name: util packages install
  yum: name={{ util_packages }}
       state=latest

