---
- name: nginx_startup
  command: systemctl enable nginx

- name: php-fpm_startup
  command: systemctl enable php-fpm

- name: zabbix_server_startup
  command: systemctl enable zabbix-server

- name: nginx_restart
  command: systemctl restart nginx

- name: php-fpm_restart
  command: systemctl restart php-fpm

- name: zabbix_server_restart
  command: systemctl restart zabbix-server

- name: firewall_reload
  command: firewall-cmd --reload
