---
- hosts: db-node-1.dl.local
  user: root
  vars:
    DBName: zabbix
    DBUser: zabbix
    DBPassword: password
    database_creation: True
  tasks:
    - name: Python-psycopg2 install
      yum: name="python-psycopg2"
           state=present

    - name: Create database user
      postgresql_user: name={{ DBUser }}
                       password={{ DBPassword }}
      sudo: yes
      sudo_user: postgres
      when: database_creation

    - name: Create database"
      postgresql_db: name={{ DBName }}
                     owner={{ DBUser }}
                     encoding='UTF-8'
                     lc_collate='en_US.UTF-8'
                     lc_ctype='en_US.UTF-8'
                     template='template0'
      sudo: yes
      sudo_user: postgres
      when: database_creation
