---
- hosts: zabbix-node-1.dl.local
  user: root
  vars:
    DBHost: 192.168.0.250
    DBName: zabbix
    DBUser: zabbix
    DBPassword: password
    database_sqlload: True
  tasks:

    - name: Importing schema file
      shell: "cd /usr/share/doc/zabbix-server-pgsql-2.4.6/create && psql -h '{{ DBHost }}' -U '{{ DBUser }}' -d '{{ DBName }}' -f schema.sql && touch /etc/zabbix/schema.done"
      args:
        creates: /etc/zabbix/schema.done
      environment:
        PGPASSWORD: '{{ DBPassword }}'
      when: database_sqlload

    - name: Importing images file
      shell: "cd /usr/share/doc/zabbix-server-pgsql-2.4.6/create && psql -h '{{ DBHost }}' -U '{{ DBUser }}' -d '{{ DBName }}' -f images.sql && touch /etc/zabbix/images.done"
      args:
        creates: /etc/zabbix/images.done
      environment:
        PGPASSWORD: '{{ DBPassword }}'
      when: database_sqlload

    - name: Importing data file
      shell: "cd /usr/share/doc/zabbix-server-pgsql-2.4.6/create && psql -h '{{ DBHost }}' -U '{{ DBUser }}' -d '{{ DBName }}' -f data.sql && touch /etc/zabbix/data.done"
      args:
        creates: /etc/zabbix/data.done
      environment:
        PGPASSWORD: '{{ DBPassword }}'
      when: database_sqlload
