---
- name: links create | libicuuc.so (x64)
  file: src=/usr/lib64/libicuuc.so
        dest=/usr/local/lib64/libicuuc.so.46
        state=link

- name: links create | libicuuc.so (x32)
  file: src=/usr/lib64/libicuuc.so
        dest=/usr/local/lib/libicuuc.so.46
        state=link

- name: links create | libicudata.so (x64)
  file: src=/usr/lib64/libicudata.so
        dest=/usr/local/lib64/libicudata.so.46
        state=link

- name: links create | libicudata.so (x32)
  file: src=/usr/lib64/libicudata.so
        dest=/usr/local/lib/libicudata.so.46
        state=link

- name: links create | libicui18n.so (x64)
  file: src=/usr/lib64/libicui18n.so
        dest=/usr/local/lib64/libicui18n.so.46
        state=link

- name: links create | libicui18n.so (x32)
  file: src=/usr/lib64/libicui18n.so
        dest=/usr/local/lib/libicui18n.so.46
        state=link
