---
- name: Additional packages install
  yum: name={{ item }}
       state=present
  with_items: AdditionalPackages

- include: build-packages.yml

- name: Postgres packages install
  yum: name={{ item }}
       state=present
  with_items: PostgresPackages

- include: postgres-config.yml

- name: Firewall configure | port open
  firewalld: zone=public service=postgresql permanent=true state=enabled
  notify:
    - firewall_reload

- name: Start postgresql service
  service: name=postgresql-9.4
           state=started
           enabled=yes
