- name: Create Physical Volume on /dev/sdb
  command: pvcreate {{ pg_disk }}

- name: Create volume group on the disks
  lvg: vg=pg_storage pvs={{ pg_disk }}

- name: Create logical volume named metadata
  lvol: vg=pg_storage lv=pg_data size=100%FREE